# Generated by Django 3.1 on 2020-08-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTrackApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='displayname',
        ),
    ]
